#!/usr/bin/env bash

set -euxo pipefail

if [[ $# -gt 0 ]]; then
  echo "
  Usage: ${0##*/}
  Builds and installs Orion Studio into ~/.local, making it available as ~/.local/bin/orion-studio.

  Before running this you should ensure you have all the build dependencies installed with `./script/linux`.
  "
  exit 1
fi
export ORION_STUDIO_CHANNEL=$(<crates/zed/RELEASE_CHANNEL)
export ORION_STUDIO_UPDATE_EXPLANATION="You need to fetch and rebuild Orion Studio in $(pwd)"
script/bundle-linux

arch="$(uname -m)"
commit=$(git rev-parse HEAD | cut -c 1-7)
archive="orion-studio-linux-${arch}.tar.gz"
export ORION_STUDIO_BUNDLE_PATH="${CARGO_TARGET_DIR:-target}/release/${archive}"
script/install.sh
