#!/usr/bin/env bash

set -euxo pipefail

if [ "$#" -ne 1 ]; then
  echo "Usage: $0 <release_version>"
  exit 1
fi

mkdir -p snap/gui

export DO_STARTUP_NOTIFY="true"
export APP_NAME="Orion Studio"
export APP_CLI="orion-studio"
export APP_ICON="\${SNAP}/meta/gui/orion-studio.png"
export APP_ARGS="%U"
envsubst < "crates/zed/resources/orion-studio.desktop.in" \
  | sed '/^# To add Orion Studio /d; /^# Upstream reports describe /d; /^# If this happens /d' \
  > "snap/gui/orion-studio.desktop"
cp "crates/zed/resources/app-icon.png" "snap/gui/orion-studio.png"

RELEASE_VERSION="$1" envsubst < crates/zed/resources/snap/snapcraft.yaml.in > snap/snapcraft.yaml

# Clean seems to be needed to actually check that the snapcraft.yaml
# works.  For example, when a `stage-package` is removed, it will
# still remain on rebuild.
snapcraft clean

snapcraft
